# Generated by Django 4.0.1 on 2022-01-29 15:45

from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.CharField(max_length=200)),
                (
                    "short_url",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("subpart", models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
