# Generated by Django 4.0.1 on 2022-01-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortenurl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="long_url",
            field=models.CharField(max_length=2000),
        ),
    ]
